Sakshi Bhavsar (sgb9086)

N10793425

Data Science Bootcamp Week 2 HomeWork

In [7]:
import numpy as np

# Load the iris dataset
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0, 1, 2, 3])

# 1. Define two custom numpy arrays, A and B
A = np.array([1, 2, 3, 4, 5])
B = np.array([4, 5, 6, 7, 8])

# Stack A and B vertically and horizontally
vertical_stack = np.vstack((A, B))
horizontal_stack = np.hstack((A, B))

print("Vertically Stacked:\n", vertical_stack)
print("Horizontally Stacked:\n", horizontal_stack)

# 2. Find common elements between A and B (intersection)
common_elements = np.intersect1d(A, B)
print("Common Elements:", common_elements)

# 3. Extract numbers from A within range [5, 10]
filtered_A = A[(A >= 5) & (A <= 10)]
print("Filtered A within range [5, 10]:", filtered_A)

# 4. Filter rows where petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
filtered_iris = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print("Filtered Iris Data:\n", filtered_iris)


Vertically Stacked:
 [[1 2 3 4 5]
 [4 5 6 7 8]]
Horizontally Stacked:
 [1 2 3 4 5 4 5 6 7 8]
Common Elements: [4 5]
Filtered A within range [5, 10]: [5]
Filtered Iris Data:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [8]:
import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# 1. Filter 'Manufacturer', 'Model' and 'Type' for every 20th row starting from row 0
filtered_df = df.iloc[::20, :][['Manufacturer', 'Model', 'Type']]
print("Filtered Rows:\n", filtered_df)

# 2. Replace missing values in Min.Price and Max.Price with their respective mean
df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)
print("Missing values replaced.")

# 3. Get rows with row sum > 100
df_random = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
row_sum_filtered = df_random[df_random.sum(axis=1) > 100]
print("Rows with sum > 100:\n", row_sum_filtered)


Filtered Rows:
    Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small
Missing values replaced.
Rows with sum > 100:
      0   1   2   3
0   25  39  21  29
1   17  38  37  29
4   28  38  16  21
8   39  20  24  25
13  34  21  31  24


<ipython-input-8-f44631f53c87>:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
<ipython-input-8-f44631f53c87>:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True